FROM amlwwalker/beego
MAINTAINER Alex Walker amlwwalker@gmail.com

RUN go get github.com/astaxie/beego
RUN go get github.com/beego/bee
RUN go get github.com/tools/godep
RUN go get golang.org/x/oauth2
RUN go get golang.org/x/oauth2/google
RUN go get github.com/jinzhu/gorm
RUN go get github.com/jinzhu/gorm/dialects/postgres
RUN go get github.com/stripe/stripe-go
RUN go get github.com/stripe/stripe-go/charge
RUN go get golang.org/x/crypto/bcrypt
RUN go get github.com/ventu-io/go-shortid
RUN go get github.com/astaxie/beego/session/redis
RUN go get gopkg.in/yaml.v2



